name: build and deploy jobs
on:
  workflow_call:
    inputs:
      build_source:
        description: source directory for build
        required: false 
        type: string
        default: ''
      build_destination:
        description: destination directory for build
        required: false 
        type: string
        default: _site
      sparse_checkout:
        description: action/checkout only selected directory
        required: false 
        type: string
        default: true 
      builder:
        description: type of builder
        required: false 
        type: string
        default: ''
      deploy_to:
        description: site host type
        required: false 
        type: string
        default: gh-pages
jobs:
  # Build job
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: exit job if no builder
        run: |
          if: ${{inputs.builder!=''}}; then
          echo "No builder found, exiting job."
          exit 1
          fi
      - name: list contents before repo checkout
        run: |
          ls -al ${{ github.workspace }}
      - name: checkout file
        uses: actions/checkout@v4
        # sparse checkout below doesn't work, it doesn't checkout level1 directory, bug?
        if: inputs.sparse_checkout
        with:
          sparse-checkout: |
            ${{inputs.build_source}}
        # cone mode false means will checkout only the file/files mentioned in the path
        # default is true which checks out repository root level files unnecessarily for our case
          sparse-checkout-cone-mode: false  
      - name: list contents after repo checkout
        run: |
          ls -al ${{ github.workspace }}
          ls -al ${{ github.workspace }}/${{inputs.build_source}}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        if: inputs.builder == 'jekyll' 
        uses: actions/jekyll-build-pages@v1
        with:
          source: ${{inputs.build_source}}
          destination: ${{inputs.build_destination}}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{inputs.build_destination}}
  deploy:
    if: inputs.deploy_to == 'gh-pages'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
